defaults:
  - 'strategy_schema'
  - cfg: cgsv
  - _self_

_target_: feduciary.strategy.cgsvstrategy.CgsvStrategy
cfg:
  train_fraction: 1.0
  eval_fraction: 1.0
  delta_normalize: true
  beta: 1.5
  alpha: 0.95
  gamma: 0.15

