defaults:
  - 'strategy_schema'
  - cfg: fedstdev_strategy
  - _self_

_target_: feduciary.strategy.fedgradstdstrategy.FedgradstdStrategy
cfg:
  train_fraction: 1.0
  eval_fraction: 1.0
  betas:
    - 1e3
    - 1e3
    - 1e4
    - 1e3
    - 1e4
    - 1e3
    - 1e3
    - 1e3
  alpha: 0.2
  num_clients: ${simulator.num_clients}
  weighting_strategy: grad_sigma_by_mu_layer_wise