defaults:
  - 'strategy_schema'
  - cfg: fedstdev_strategy
  - _self_

_target_: feduciary.strategy.fedgradstdstrategy.FedgradstdStrategy
cfg:
  train_fraction: 1.0
  eval_fraction: 1.0
  betas:
    - 1
    - 1
    - 0.1
    - 1
    - 0.1
    - 1
    - 1
    - 1
  beta_0: 1.0
  alpha: 0.2
  num_clients: ${simulator.num_clients}
  # weighting_strategy: grad_sigma_by_mu_layer_wise
  # weighting_strategy: grad_sigma_by_mu_scalar_wtd_avg
  # weighting_strategy: grad_sigma_by_mu_full_dim
  weighting_strategy: grad_sigma_direction_trial

