defaults:
  - base_flower_server
  - _self_

_target_: src.server.baseflowerserver.BaseFlowerServer
_partial_: true
cfg:
  eval_every: ${simulator.eval_every}
  eval_type: ${simulator.eval_type}
train_cfg: ${train_cfg}
