defaults:
  - base_server
  - cfg: base_cgsv
  - _self_

_target_: src.server.cgsvserver.CgsvServer
_partial_: true
cfg:
  sampling_fraction: 1.0
  rounds: 1
  eval_type: both
  eval_fraction: 1.0
  eval_every: 1
  beta: 1.5
  alpha: 0.95
  gamma: 1.5
  multiprocessing: false
client_cfg: ${client.cfg}
