defaults:
  - base_server
  - cfg: base_fedavg
  - _self_

_target_: src.server.fedavgserver.FedavgServer
_partial_: true
cfg:
  sampling_fraction: 1.0
  # server_lr: 1.0
  update_rule: param_average
  rounds: ${simulator.num_rounds}
  eval_type: both
  eval_fraction: 1.0
  eval_every: 1
  momentum: 0.0
  multiprocessing: false
client_cfg: ${client.cfg}
