defaults:
  - base_server
  - cfg: fedstdev_server
  - _self_

_target_: src.server.fedstdevserver.FedstdevServer
_partial_: true
cfg:
  sampling_fraction: 1.0
  rounds: ${simulator.num_rounds}
  eval_type: both
  eval_fraction: 1.0
  eval_every: 1
  alpha: 0.8
  gamma: 0.95
  delta_normalize: False
  betas: 
    - 1e3
    - 1e3
    - 1e4
    - 1e3
    - 1e4
    - 1e3
    - 1e3
    - 1e3
  multiprocessing: false
  weight_scaling: tanh
client_cfg: ${client.cfg}
