defaults:
  - client_schema
  - cfg: base_client
  - _self_

_target_: feduciary.client.baseflowerclient.BaseFlowerClient
_partial_: true
cfg:
  start_epoch: 0
  data_shuffle: true
train_cfg: ${train_cfg}