defaults:
  - client_schema
  - cfg: base_client
  - _self_

_target_: src.client.baseflowerclient.BaseFlowerClient
_partial_: true
cfg:
  epochs: 1
  start_epoch: 0
  device: auto
  batch_size: 32
  lr: 0.01
  lr_decay: 0.977
  optimizer:
    _target_: torch.optim.SGD
    _partial_: true
    lr: ${client.cfg.lr}
  criterion:
    _target_: torch.nn.CrossEntropyLoss
  lr_scheduler:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    _partial_: true
    gamma: ${client.cfg.lr_decay}

  shuffle: false
  metric_cfg:
    eval_metrics: ['acc1']
    file_prefix: ''
    log_to_file: false