%YAML 1.2
---
# Experiment mode: Switch between debug and experiment mode
mode: fedavg

# Description: A string to describe the intent of the run
desc: 'Testing parameters with gradient average for 100 iterations'

# Log Configuration: Additional configurations to be copied in the results summary section. Must be a valid configuration from the config tree.
log_conf: [client.cfg.lr]

defaults:
  - base_config
  - hydra: custom
  - server: fedavg
  - client: base
  # - train: base_trainer
  - _self_

server:
  cfg:
    update_rule: gradient_average

simulator:
  seed: 42
  use_tensorboard: false
  use_wandb: true
  save_csv: false
  num_clients: 5
  num_rounds: 100
  checkpoint_every: 20
  # Simulator Mode: Takes arguments 'federated', 'standalone' or 'centralized'
  mode: federated

dataset:
  name: CIFAR10
  data_path: data/
  test_fraction: 0.2
  split_type: iid
  num_clients: ${simulator.num_clients}
  subsample: false
  subsample_fraction: 1.0
  # Noise parameter is specific to one patho client
  noise:
    mu: 0.0
    sigma: 0.5
    flip_percent: 1.0
  transforms:
    resize:
      _target_: torchvision.transforms.Resize
      size: 
        - 28
        - 28

model:
  name: TwoCNN
  init_type: xavier
  init_gain: 1.0
  dropout: 0.0
  model_spec:           # Optional model spec provided for quick tuning
    _target_: src.models.twocnn.TwoCNN
    _partial_: false
    hidden_size: 200
    in_channels: null
    num_classes: null 

# Overrides
client:
  cfg:
    batch_size: 256
    epochs: 1
#     shuffle: false
#     eval_metrics: ['acc1']

...