%YAML 1.2
---
# Make sure mode matches the experiment config for full runs
mode: varagg
log_conf: [client.cfg.lr]

defaults:
  - base_config
  - hydra: custom
  - server: varagg
  - client: varagg
  # - train: base_trainer
  - _self_

simulator:
  seed: 42
  use_tensorboard: true
  use_wandb: true
  num_clients: 5
  num_rounds: 200
  checkpoint_every: 10

dataset:
  name: CIFAR10
  data_path: data/
  test_fraction: 0.2
  split_type: iid
  K: ${simulator.num_clients}
  subsample: 1.0
  transforms:
    resize:
      _target_: torchvision.transforms.Resize
      size: 
        - 28
        - 28

model:
  name: TwoCNN
  init_type: xavier
  init_gain: 1.0
  dropout: 0.0
  model_spec:           # Optional model spec provided for quick tuning
    _target_: src.models.twocnn.TwoCNN
    _partial_: false
    hidden_size: 200
    in_channels: null
    num_classes: null 

# Overrides

client:
  cfg:
    batch_size: 256
    epochs: 1
#     shuffle: false
#     eval_metrics: ['acc1']
  # train_cfg: ${train}


# hydra:
  # job:
  #   name: ${mode}_${dataset.name}
  #   chdir: true
  # run:
  #   dir: outputs/${now:%Y-%m-%d}_${hydra.job.name}/${now:%H-%M-%S}_${hydra.job.override_dirname}
  # sweep:
  #   dir: outputs/${now:%Y-%m-%d}_${hydra.job.name}/${now:%H-%M-%S}
  #   subdir: ${hydra.job.override_dirname}
...