%YAML 1.2
---
# Experiment mode: Switch between debug and experiment runs. Debug mode overrides certain configs. Other modes are used as a one word tag for the experiment type
mode: varagg

# Description: A string to describe the intent of the run
desc: 'scaled tanh  variance agg. with 75 % label flipping'

# Log Configuration: Additional configurations to be copied in the results summary section. Must be a valid configuration from the config tree.
log_conf: [client.cfg.lr]

defaults:
  - base_config
  - hydra: custom
  - server: varagg
  - client: varagg
  # - train: base_trainer
  - _self_

simulator:
  seed: 42
  use_tensorboard: true
  use_wandb: true
  num_clients: 5
  num_rounds: 150
  checkpoint_every: 10
  # Simulator Mode: Takes arguments 'federated', 'standalone' or 'centralized'
  mode: federated

dataset:
  name: CIFAR10
  data_path: data/
  test_fraction: 0.2
  split_type: one_label_flipped_client
  num_clients: ${simulator.num_clients}
  subsample: 1.0
  # Noise parameter is specific to one patho client
  noise:
    mu: 0.0
    sigma: 0.5
    flip_percent: 0.75
  transforms:
    resize:
      _target_: torchvision.transforms.Resize
      size: 
        - 28
        - 28

model:
  name: TwoCNN
  init_type: xavier
  init_gain: 1.0
  dropout: 0.0
  model_spec:           # Optional model spec provided for quick tuning
    _target_: src.models.twocnn.TwoCNN
    _partial_: false
    hidden_size: 200
    in_channels: null
    num_classes: null 

# Overrides
client:
  cfg:
    batch_size: 256
    epochs: 1
#     shuffle: false
#     eval_metrics: ['acc1']

...