%YAML 1.2
---
# Experiment mode: Switch between debug and experiment mode
mode: debug
# Description: A string to describe the intent of the run
desc: 'FedStdev rerun with 1 epoch, imbalanced cl0, sigma/mu weights'
# desc: 'FedAvg rerun with fix delta normalize, iid, with delta_normalize'

defaults:
  - base_config
  - hydra: custom
  - server: fedstdev
  - client: fedstdev
  # - train: base_trainer
  - _self_

# Overrides
client:
  cfg:
    batch_size: 256
    epochs: 1
    device: auto

server:
  cfg:
    delta_normalize: false
    # weighting_strategy: tanh
    weighting_strategy: tanh_sigma_by_mu


simulator:
  seed: 42
  use_tensorboard: false
  use_wandb: true
  save_csv: false
  num_clients: 5
  num_rounds: 150
  checkpoint_every: 20
  plot_every: 2  # REMOVE ME
  # Simulator Mode: Takes arguments 'federated', 'standalone' or 'centralized'
  mode: federated

dataset:
  name: CIFAR10
  data_path: data/
  subsample: false
  subsample_fraction: 1.0
  transforms:
    resize:
      _target_: torchvision.transforms.Resize
      size: 
        - 28
        - 28

  split_conf:
    # split_type: one_label_flipped_client
    split_type: one_imbalanced_client
    # split_type: one_noisy_client
    num_splits: ${simulator.num_clients}
    # Noise parameter is specific to one patho client
    test_fraction: 0.2 # Client train-test split

    noise:
      mu: 0.0
      sigma: 0.5
      flip_percent: 1.0
  

model:
  name: TwoCNN
  init_type: xavier
  init_gain: 1.0
  dropout: 0.0
  model_spec:           # Optional model spec provided for quick tuning
    _target_: src.models.twocnn.TwoCNN
    _partial_: false
    hidden_size: 200
    # Option to override in_channels and num_classes. Otherwise auto set by the dataset
    in_channels: null
    num_classes: null 


# Log Configuration: Additional configurations to be copied in the results summary section. Must be a valid configuration from the config tree.
log_conf: []

...