%YAML 1.2
---
simulator:
  exp_prefix: default_
  seed: 42
  data_path: data/
  result_path: result/
  use_tb: true
  num_clients: 5
  rounds: 10
  eval_type: both
  eval_fraction: 1.0
  eval_every: 1
  algorithm: fedavg

client:
  epochs: 5
  device: cuda
  batch_size: 32
  optimizer: SGD
  criterion: CrossEntropyLoss
  lr: 0.01
  lr_decay: null
  no_shuffle: true

server:
  sampling_fraction: 1.0

metrics:
  eval_metrics: ['acc1', 'acc5', 'mse']
  fairness_metrics: []

model:
  name: TwoCNN
  init_type: xavier
  init_gain: 1.0
  dropout: 0.0
  model_spec:           # Optional model spec provided for quick tuning
    num_layers: 2
    layer1:
      dim: 512
    embedding:
      dim: 10


dataset:
  dataset: MNIST
  test_fraction: 0.2
  split_type: iid
  resize: 28
  imnorm: false
  rand_rot: null
  rand_hf: null
  rand_vf: null
  rand_jit: null

...